name: Check Tournaments

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-tournaments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run playtomic-watch T
        run: >
          go run ./cmd/playtomic-watch
          --config configs/t-config.yaml
          --telegram-token "$TELEGRAM_BOT_TOKEN"
          --telegram-chat-id "$TELEGRAM_CHAT_ID"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Run playtomic-watch K
        run: >
          go run ./cmd/playtomic-watch
          --config configs/k-config.yaml
          --telegram-token "$TELEGRAM_BOT_TOKEN"
          --telegram-chat-id 844005776
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
